main: main.o ItemType.o CircularLinkedList.o
        $(CXX) $(CXXFLAGS) -o main main.o ItemType.o CircularLinkedList.o
main.o: main.cpp ItemType.h CircularLinkedList.h
		$(CXX) $(CXXFLAGS) -c main.cpp
CircularLinkedList.o: CircularLinkedList.h ItemType.h
# Customer.h
	# $(CXX) $(CXXFLAGS) -c main.cpp

clean:
	rm -rf *.o
	rm -rf main
compile:
	g++ -std=c++0x -o main *.cpp
run:
	./main input1.txt


